In [33]:
import pandas as pd
import numpy as np

# Reading the data from the CSV file
data = pd.read_csv(r'C:\Users\ghadf\OneDrive\Desktop\Data Analytics\Python\data\nba\23_24\23_24_season_games.csv')

# Split the data into two separate DataFrames for home and away
home_data = data[['DATE', 'Start (ET)', 'Home/Neutral']].copy()
home_data['Home_Away'] = 'Home'
home_data['MATCHUP'] = home_data['Home/Neutral'] + ' vs. ' + data['Visitor/Neutral']
home_data.rename(columns={'Home/Neutral': 'Team'}, inplace=True)
home_data['WL_encoded'] = np.nan  # Placeholder for predictions or actual results

away_data = data[['DATE', 'Start (ET)', 'Visitor/Neutral']].copy()
away_data['Home_Away'] = 'Away'
away_data['MATCHUP'] = home_data['Team'] + ' vs. ' + away_data['Visitor/Neutral']
away_data.rename(columns={'Visitor/Neutral': 'Team'}, inplace=True)
away_data['WL_encoded'] = np.nan  # Placeholder for predictions or actual results

# Union/Concatenate the two DataFrames
final_data = pd.concat([home_data, away_data], ignore_index=True)

# Sorting the data by Date, Start time, and Home/Away status
final_data.sort_values(by=['DATE', 'Start (ET)', 'Home_Away'], inplace=True)

#reset the index
final_data.reset_index(drop=True, inplace=True)
print(final_data)

# Write the data to a CSV file
#final_data.to_csv(r'C:\Users\ghadf\OneDrive\Desktop\Data Analytics\Python\ML\nba_w_l_prediction_models\nba_analysis\data\23_24_season_games.csv', index=False)

                   DATE Start (ET)                    Team Home_Away  \
0     Fri, Apr 12, 2024     10:00p    New Orleans Pelicans      Away
1     Fri, Apr 12, 2024     10:00p         Houston Rockets      Away
2     Fri, Apr 12, 2024     10:00p   Golden State Warriors      Home
3     Fri, Apr 12, 2024     10:00p  Portland Trail Blazers      Home
4     Fri, Apr 12, 2024     10:30p               Utah Jazz      Away
...                 ...        ...                     ...       ...
2395  Wed, Oct 25, 2023      8:00p           Chicago Bulls      Home
2396  Wed, Oct 25, 2023      9:00p        Sacramento Kings      Away
2397  Wed, Oct 25, 2023      9:00p               Utah Jazz      Home
2398  Wed, Oct 25, 2023      9:30p        Dallas Mavericks      Away
2399  Wed, Oct 25, 2023      9:30p       San Antonio Spurs      Home

                                             MATCHUP  WL_encoded
0     Golden State Warriors vs. New Orleans Pelicans         NaN
1         Portland Trail Blazers vs. Houston Rockets         NaN
2     Golden State Warriors vs. New Orleans Pelicans         NaN
3         Portland Trail Blazers vs. Houston Rockets         NaN
4                 Los Angeles Clippers vs. Utah Jazz         NaN
...                                              ...         ...
2395         Chicago Bulls vs. Oklahoma City Thunder         NaN
2396                  Utah Jazz vs. Sacramento Kings         NaN
2397                  Utah Jazz vs. Sacramento Kings         NaN
2398          San Antonio Spurs vs. Dallas Mavericks         NaN
2399          San Antonio Spurs vs. Dallas Mavericks         NaN

[2400 rows x 6 columns]

In [34]:
import pandas as pd

# Assuming you've already read in your df1
df1 = pd.read_csv(r'C:\Users\ghadf\OneDrive\Desktop\Data Analytics\Python\ML\nba_w_l_prediction_models\nba_analysis\data\team_ids.csv')

# Filter df1 to only unique TEAM_ID, TEAM_NAME, and SEASON_ID
unique_teams = df1[['TEAM_NAME', 'TEAM_ID', 'TEAM_ABBREVIATION']].drop_duplicates()

#change team name "LA Clippers" to "Los Angeles Clippers"
unique_teams['TEAM_NAME'] = unique_teams['TEAM_NAME'].replace('LA Clippers', 'Los Angeles Clippers')

# get unique values from team_id and season_id columns
unique_team_ids = unique_teams['TEAM_ID'].unique()
print(unique_team_ids)
unique_team_names = unique_teams['TEAM_NAME'].unique()
print(unique_team_names)
unique_team_names = unique_teams['TEAM_ABBREVIATION'].unique()
print(unique_team_names)

#take only the columns team_id, team_name, season_id, and game_id

#print(df1.head())

# Assuming df1 has been read in and unique_teams has been created
team_to_abbreviation = dict(zip(unique_teams['TEAM_NAME'], unique_teams['TEAM_ABBREVIATION']))

print(team_to_abbreviation)

[1610612737 1610612738 1610612739 1610612740 1610612741 1610612742
 1610612743 1610612744 1610612745 1610612746 1610612747 1610612748
 1610612749 1610612750 1610612751 1610612752 1610612753 1610612754
 1610612755 1610612756 1610612757 1610612758 1610612759 1610612760
 1610612761 1610612762 1610612763 1610612764 1610612765 1610612766]
['Atlanta Hawks' 'Boston Celtics' 'Cleveland Cavaliers'
 'New Orleans Pelicans' 'Chicago Bulls' 'Dallas Mavericks'
 'Denver Nuggets' 'Golden State Warriors' 'Houston Rockets'
 'Los Angeles Clippers' 'Los Angeles Lakers' 'Miami Heat'
 'Milwaukee Bucks' 'Minnesota Timberwolves' 'Brooklyn Nets'
 'New York Knicks' 'Orlando Magic' 'Indiana Pacers' 'Philadelphia 76ers'
 'Phoenix Suns' 'Portland Trail Blazers' 'Sacramento Kings'
 'San Antonio Spurs' 'Oklahoma City Thunder' 'Toronto Raptors' 'Utah Jazz'
 'Memphis Grizzlies' 'Washington Wizards' 'Detroit Pistons'
 'Charlotte Hornets']
['ATL' 'BOS' 'CLE' 'NOP' 'CHI' 'DAL' 'DEN' 'GSW' 'HOU' 'LAC' 'LAL' 'MIA'
 'MIL' 'MIN' 'BKN' 'NYK' 'ORL' 'IND' 'PHI' 'PHX' 'POR' 'SAC' 'SAS' 'OKC'
 'TOR' 'UTA' 'MEM' 'WAS' 'DET' 'CHA']
{'Atlanta Hawks': 'ATL', 'Boston Celtics': 'BOS', 'Cleveland Cavaliers': 'CLE', 'New Orleans Pelicans': 'NOP', 'Chicago Bulls': 'CHI', 'Dallas Mavericks': 'DAL', 'Denver Nuggets': 'DEN', 'Golden State Warriors': 'GSW', 'Houston Rockets': 'HOU', 'Los Angeles Clippers': 'LAC', 'Los Angeles Lakers': 'LAL', 'Miami Heat': 'MIA', 'Milwaukee Bucks': 'MIL', 'Minnesota Timberwolves': 'MIN', 'Brooklyn Nets': 'BKN', 'New York Knicks': 'NYK', 'Orlando Magic': 'ORL', 'Indiana Pacers': 'IND', 'Philadelphia 76ers': 'PHI', 'Phoenix Suns': 'PHX', 'Portland Trail Blazers': 'POR', 'Sacramento Kings': 'SAC', 'San Antonio Spurs': 'SAS', 'Oklahoma City Thunder': 'OKC', 'Toronto Raptors': 'TOR', 'Utah Jazz': 'UTA', 'Memphis Grizzlies': 'MEM', 'Washington Wizards': 'WAS', 'Detroit Pistons': 'DET', 'Charlotte Hornets': 'CHA'}

1610612737, 1610612738, 1610612739, 1610612740, 1610612741, 1610612742, 1610612743, 1610612744, 1610612745, 1610612746, 1610612747, 1610612748, 1610612749, 1610612750, 1610612751, 1610612752, 1610612753, 1610612754, 1610612755, 1610612756, 1610612757, 1610612758, 1610612759, 1610612760, 1610612761, 1610612762, 1610612763, 1610612764, 1610612765, 1610612766

current_teams = [1610612739, 1610612737, 1610612738, 1610612740, 1610612741, 1610612742, 1610612743, 1610612744, 1610612745, 1610612746, 1610612747, 1610612748, 1610612749, 1610612750, 1610612751, 1610612752, 1610612753, 1610612754, 1610612755, 1610612756, 1610612757, 1610612758, 1610612759, 1610612760, 1610612761, 1610612762, 1610612763, 1610612764, 1610612765, 1610612766]

In [35]:


# Convert 'Date' column to datetime format in final_data
final_data['DATE'] = pd.to_datetime(final_data['DATE'])


# Merge final_data with unique_teams on the team names to get the TEAM_ID. Use 'left' to ensure final_data size isn't increased.
final_data = final_data.merge(unique_teams, left_on='Team', right_on='TEAM_NAME', how='left')


#count nan values
final_data.isnull().sum()
#view the team_id columns that have nan values
final_data[final_data['TEAM_ID'].isnull()]

Empty DataFrame
Columns: [DATE, Start (ET), Team, Home_Away, MATCHUP, WL_encoded, TEAM_NAME, TEAM_ID, TEAM_ABBREVIATION]
Index: []

In [36]:


# Convert TEAM_ID and SEASON_ID to integers
#final_data['TEAM_ID'] = final_data['TEAM_ID'].astype(int)
#final_data['SEASON_ID'] = final_data['SEASON_ID'].astype(int)

# If you want to convert them to strings after converting to integers, uncomment the following lines:
# final_data['TEAM_ID'] = final_data['TEAM_ID'].astype(str)
# final_data['SEASON_ID'] = final_data['SEASON_ID'].astype(str)

# Drop 'TEAM_NAME' and 'Start (ET)' column as it's redundant
final_data.drop(['TEAM_NAME', 'Start (ET)'], axis=1, inplace=True)

final_data['TEAM_ID'] = final_data['TEAM_ID'].astype('int64')

# Assuming your dataframe is named 'final_data'
final_data['YEAR'] = pd.to_datetime(final_data['DATE']).dt.year
final_data['MONTH'] = pd.to_datetime(final_data['DATE']).dt.month
final_data['DAY'] = pd.to_datetime(final_data['DATE']).dt.day

# Dropping the original Date column and Team, Home_Away, Matchup columns
final_data.drop(['DATE', 'Team'], axis=1, inplace=True)

print(final_data)

     Home_Away                                         MATCHUP  WL_encoded  \
0         Away  Golden State Warriors vs. New Orleans Pelicans         NaN
1         Away      Portland Trail Blazers vs. Houston Rockets         NaN
2         Home  Golden State Warriors vs. New Orleans Pelicans         NaN
3         Home      Portland Trail Blazers vs. Houston Rockets         NaN
4         Away              Los Angeles Clippers vs. Utah Jazz         NaN
...        ...                                             ...         ...
2395      Home         Chicago Bulls vs. Oklahoma City Thunder         NaN
2396      Away                  Utah Jazz vs. Sacramento Kings         NaN
2397      Home                  Utah Jazz vs. Sacramento Kings         NaN
2398      Away          San Antonio Spurs vs. Dallas Mavericks         NaN
2399      Home          San Antonio Spurs vs. Dallas Mavericks         NaN

         TEAM_ID TEAM_ABBREVIATION  YEAR  MONTH  DAY
0     1610612740               NOP  2024      4   12
1     1610612745               HOU  2024      4   12
2     1610612744               GSW  2024      4   12
3     1610612757               POR  2024      4   12
4     1610612762               UTA  2024      4   12
...          ...               ...   ...    ...  ...
2395  1610612741               CHI  2023     10   25
2396  1610612758               SAC  2023     10   25
2397  1610612762               UTA  2023     10   25
2398  1610612742               DAL  2023     10   25
2399  1610612759               SAS  2023     10   25

[2400 rows x 8 columns]

In [37]:
def replace_team_names_with_abbreviations(row):
    matchup_str = row['MATCHUP']
    for team, abbreviation in team_to_abbreviation.items():
        matchup_str = matchup_str.replace(team, abbreviation)
    
    # If the team is Away, replace "vs." with "@"
    if row['Home_Away'] == 'Away':
        matchup_str = matchup_str.replace(" vs. ", " @ ")
    return matchup_str

final_data['MATCHUP'] = final_data.apply(replace_team_names_with_abbreviations, axis=1)
print(final_data)

     Home_Away      MATCHUP  WL_encoded     TEAM_ID TEAM_ABBREVIATION  YEAR  \
0         Away    GSW @ NOP         NaN  1610612740               NOP  2024
1         Away    POR @ HOU         NaN  1610612745               HOU  2024
2         Home  GSW vs. NOP         NaN  1610612744               GSW  2024
3         Home  POR vs. HOU         NaN  1610612757               POR  2024
4         Away    LAC @ UTA         NaN  1610612762               UTA  2024
...        ...          ...         ...         ...               ...   ...
2395      Home  CHI vs. OKC         NaN  1610612741               CHI  2023
2396      Away    UTA @ SAC         NaN  1610612758               SAC  2023
2397      Home  UTA vs. SAC         NaN  1610612762               UTA  2023
2398      Away    SAS @ DAL         NaN  1610612742               DAL  2023
2399      Home  SAS vs. DAL         NaN  1610612759               SAS  2023

      MONTH  DAY
0         4   12
1         4   12
2         4   12
3         4   12
4         4   12
...     ...  ...
2395     10   25
2396     10   25
2397     10   25
2398     10   25
2399     10   25

[2400 rows x 8 columns]

In [38]:
# Read in the data for averages from X after it's dropped the columns we don't need and just before preprocessing through encoding
#on a long short-term basis

future_season_data_stats = pd.read_csv(r'C:\Users\ghadf\OneDrive\Desktop\Data Analytics\Python\ML\nba_w_l_prediction_models\nba_analysis\data\future_season_data_stats.csv')
#print(future_season_data_stats.head())
#drop WL_encoded column
#future_season_data_stats.drop(['WL_encoded', 'TEAM_ABBREVIATION', 'MATCHUP', 'YEAR', 'MONTH', 'DAY'], axis=1, inplace=True)

print(future_season_data_stats.head())
print(len(future_season_data_stats))

      TEAM_ID Home_Away  PLUS_MINUS  PLUS_MINUS_OPP    FG_PCT   FG3_PCT  \
0  1610612737      Away   -1.587500        1.725000  0.477892  0.356283
1  1610612737      Home    2.088889       -2.088889  0.482987  0.351759
2  1610612738      Away    2.776923       -2.819231  0.466724  0.374264
3  1610612738      Home    9.129630       -9.129630  0.484382  0.375166
4  1610612739      Away    1.533333       -1.533333  0.480794  0.365217

     FT_PCT       TS%      eFG%       AST%        ORtg        PER%  \
0  0.808372  0.576064  0.538946  26.964490  113.662316  118.943719
1  0.818544  0.577641  0.540879  26.866730  114.766853  121.909224
2  0.814433  0.590361  0.556254  29.525255  114.995171  126.473609
3  0.810000  0.608431  0.573660  30.202617  117.319663  127.554010
4  0.783181  0.581633  0.546642  28.142148  113.140452  118.869372

   FG_PCT_OPP  FG3_PCT_OPP  FT_PCT_OPP   TS%_OPP  eFG%_OPP   AST%_OPP  \
0    0.486284     0.374074    0.796313  0.593874  0.557327  30.128957
1    0.483043     0.345631    0.808050  0.582409  0.547723  27.640504
2    0.462179     0.366108    0.778553  0.564355  0.529808  26.217949
3    0.456722     0.328790    0.780645  0.551227  0.518416  23.981993
4    0.476865     0.373811    0.768720  0.581462  0.545199  27.520727

         DRtg       DPER%
0  115.432612  122.895664
1  113.080216  120.370212
2  111.728857  121.160514
3  107.597700  113.547049
4  110.934592  115.473651
60

In [39]:


# Merge final_data with future_season_data_stats on TEAM_ID and Home_Away because we want to see the averages by home and away attached for the models
combined_data = pd.merge(final_data, future_season_data_stats, on=['TEAM_ID', 'Home_Away'], how='left') #, 'MATCHUP'
#print(combined_data.head())

#count nan values
#print(combined_data.isnull().sum())


#view the team_id columns that have nan values
#print(combined_data[combined_data['FG3A'].isnull()])

# drop  Home_Away_x, MATCHUP_x, TEAM_ABBREVIATION_x and change any columns that end with _y to not have _y at the end
#combined_data = combined_data.rename(columns={'Home_Away_y': 'Home_Away', 'MATCHUP_y': 'MATCHUP'})

# drop the team_abbreviaton column
combined_data.drop(['TEAM_ABBREVIATION'], axis=1, inplace=True)
print(combined_data.head())

# matchup unique values
print(combined_data['MATCHUP'].unique())

#print length of combined_data
print(len(combined_data))

# Write the data to a CSV file
combined_data.to_csv(r'C:\Users\ghadf\OneDrive\Desktop\Data Analytics\Python\ML\nba_w_l_prediction_models\nba_analysis\data\23_24_season_games_clean.csv', index=False)

  Home_Away      MATCHUP  WL_encoded     TEAM_ID  YEAR  MONTH  DAY  \
0      Away    GSW @ NOP         NaN  1610612740  2024      4   12
1      Away    POR @ HOU         NaN  1610612745  2024      4   12
2      Home  GSW vs. NOP         NaN  1610612744  2024      4   12
3      Home  POR vs. HOU         NaN  1610612757  2024      4   12
4      Away    LAC @ UTA         NaN  1610612762  2024      4   12

   PLUS_MINUS  PLUS_MINUS_OPP    FG_PCT  ...        ORtg        PER%  \
0   -1.113636        1.113636  0.474628  ...  110.438402  117.383520
1  -10.790698       10.790698  0.456935  ...  108.128195  112.773266
2    7.745098       -7.745098  0.475678  ...  114.725678  128.606069
3   -4.023810        4.019048  0.476456  ...  113.992785  115.028869
4   -3.093023        3.093023  0.472350  ...  111.558584  118.929901

   FG_PCT_OPP  FG3_PCT_OPP  FT_PCT_OPP   TS%_OPP  eFG%_OPP   AST%_OPP  \
0    0.475163     0.339421    0.784225  0.584022  0.545254  28.868661
1    0.495898     0.388558    0.803846  0.617948  0.582165  31.357502
2    0.447946     0.328317    0.767829  0.550785  0.511954  26.776788
3    0.495968     0.401890    0.783453  0.603504  0.570296  30.967742
4    0.479949     0.372062    0.771792  0.584294  0.550702  27.177522

         DRtg       DPER%
0  111.181451  115.995358
1  119.965174  127.938414
2  107.063152  113.415315
3  118.306586  126.052008
4  115.509010  122.960473

[5 rows x 25 columns]
['GSW @ NOP' 'POR @ HOU' 'GSW vs. NOP' ... 'CHI vs. OKC' 'UTA @ SAC'
 'UTA vs. SAC']
2400